# Generated by Django 5.0.3 on 2024-08-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chat_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
