# Generated by Django 5.0.3 on 2024-08-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_chat_options_alter_chat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
