# Generated by Django 5.0.3 on 2024-08-24 20:57

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_message_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_type',
        ),
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, validators=[django.core.validators.MinLengthValidator(2, message='Chat must have at least 2 members.')]),
        ),
    ]
