# Generated by Django 5.0.3 on 2024-08-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_bio_alter_user_email_alter_user_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='displayname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
