# Generated by Django 5.0.3 on 2024-08-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='displayname',
            new_name='display_name',
        ),
    ]
