# Generated by Django 5.1 on 2024-08-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_displayname_user_display_name'),
        ('core', '0008_chat_icon_alter_chat_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_typing',
        ),
        migrations.AddField(
            model_name='user',
            name='typing_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typing_users', to='core.chat'),
        ),
    ]
